### ISSUE TITLE
[Video] What is jest, run tests using jest

### ISSUE THREAD

**Issue by mjzac** [pupilfirst/wd201-scripts#154]

**Comment by mjzac** [comment]
@reenas Please review the video https://drive.google.com/drive/folders/14TPwoZHTTA9x30K-fTWBZOvwPVIwBn_b?usp=sharing

**Comment by reenas** [comment]
@mjzac Few comments in the video - 

- At 0:30 `npm install --save-dev`, the reason for using `--save-dev` is mentioned as `developer dependency`. I am unable to understand what does that mean! Also, I did a search and it is `development dependency` not developer. 
- Reg. Use of .gitignore to not track node_modules file.  Why would we want that to be not tracked?


Can you add these in Text part of the lesson?

**Comment by mjzac** [comment]
@reenas Yes, #214 will address 2 completely. 

For 1, should I re-record the video or add a banner in the video correcting what I said?

**Comment by reenas** [comment]
@mjzac - Adding a text annotation of correct term in video is enough. It would be great if you can add explanation of development dependency in text content.

**Comment by reenas** [comment]
@mjzac I have seen part 2 of the Jest video and that looks fine.
