### ISSUE TITLE
[Video] Running tests, and linting automatically as pre-commit hook using Husky, lint staged

### ISSUE THREAD

**Issue by mjzac** [pupilfirst/wd201-scripts#155]

**Comment by mjzac** [comment]
@reenas Please review the 2 part video. https://drive.google.com/drive/folders/15USuzOywJKCsAtdrAODLnH-TJf0wgtfd?usp=sharing

**Comment by reenas** [comment]
@mjzac This video is fine.

**Comment by reenas** [comment]
@mjzac These videos are fine
