### ISSUE TITLE
 L1  - What is Node.js and how to install it 

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#156]
Some feedback in [lesson](https://github.com/pupilfirst/wd201-scripts/blob/v2/introduction-to-nodejs/what-is-node-js-with-installation/README.md):

- Node.js is referred to as a framework in multiple places.
- Since importance of package.json is mentioned, can we link a resource where students can read more about it.

**Comment by reenas** [comment]
@avishekjana Can you please fix this issue with the content?

**Comment by avishekjana** [comment]
@reenas I've updated the script in those places where Node.js was referred as a framework.

But, the importance of package.json is not covered here. Which part you are refering here?

**Comment by reenas** [comment]
@avishekjana My bad, package.json is mentioned in [lesson](https://github.com/pupilfirst/wd201-scripts/blob/v2/introduction-to-nodejs/running-first-program/README.md). I have opened #164 for this.
