### ISSUE TITLE
L1 - Introduction to git

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#157]
In [Introduction to git](https://github.com/pupilfirst/wd201-scripts/blob/v2/introduction-to-nodejs/intro-to-git/README.md), a [reference link ](https://git-scm.com/download/win) to install git on Windows is mentioned. For WD courses, students use WSL/ on Windows Linux installation or Mac, so any reference should address only these to avoid confusion.

**Comment by reenas** [comment]
@avishekjana Can you please fix this issue with the content?

**Comment by avishekjana** [comment]
@reenas I've addressed the issue, please check once.
