### ISSUE TITLE
L1 - Running our first program

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#164]
@avishekjana 

I have opened a new issue for this. Since the importance of package.json is mentioned in [lesson](https://github.com/pupilfirst/wd201-scripts/blob/v2/introduction-to-nodejs/running-first-program/README.md), can we link a resource where students can read more about it.

**Comment by avishekjana** [comment]
@reenas Please check this PR: https://github.com/pupilfirst/wd201-scripts/pull/185
