### ISSUE TITLE
L2 - What are NPM scripts

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#165]
@vikispeaks In [lesson](https://github.com/pupilfirst/wd201-scripts/blob/v2/working-with-npm/npm-scripts/README.md) 
>Update the following to the scripts attribute along with the test attribute.

But the test attribute value in the final package.json content is the same as what was in the [last lesson](https://github.com/pupilfirst/wd201-scripts/blob/v2/working-with-npm/package-json-in-npm/README.md). I am unable to understand this. 

Also, `package.json` is also talked about in [L1](https://github.com/pupilfirst/wd201-scripts/blob/v2/introduction-to-nodejs/running-first-program/README.md). I believe from L2 you will show them how to create and edit package.json while L1 just introduced it.

**Comment by vikispeaks** [comment]
@reenas I see the issue. In the First Level, we introduce them to NPM. In the next, we teach about `package.json`. We move to explain how npm executes items by explaining them about script tag in npm. The test attribute and how to use it should ideally be used in the Testing levels. We are not modifying the test attribute in this lesson. We are just adding a new script along with the one auto generated by `npm init` which in this case is the Test attribute.

I also have added reference to the npm scripts docs to explore more about these in detail.
