### ISSUE TITLE
L2 - Explore built-in fs module

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#166]
@vikispeaks In [lesson](https://github.com/pupilfirst/wd201-scripts/blob/v2/working-with-npm/nodejs-fs-module/README.md):

>The writeFile is an asynchronous function, which will return immediately before the file has been written and only its callback function will be run when the write operation is completed. In the case of writeFileSync, it will block all other execution until the file has been written/created.

Can this para be explained a little. Students might not know callback. So, some explanation on asynchronous and synchronous will be good.

**Comment by vikispeaks** [comment]
@reenas Fixed with https://github.com/pupilfirst/wd201-scripts/pull/184 Please review.

**Comment by reenas** [comment]
@vikispeaks Cool!
