### ISSUE TITLE
[Video] Create an interface for accepting a new to-do.

### ISSUE THREAD

**Issue by avishekjana** [pupilfirst/wd201-scripts#170]

**Comment by avishekjana** [comment]
@reenas Please review the recording: https://drive.google.com/file/d/18VgaUN6zv6ChUzq8A9DWNDf9eb2xKMmL/view?usp=sharing

**Comment by reenas** [comment]
@avishekjana This is a thorough, well-explanatory video. I have added this to LMS now.
