### ISSUE TITLE
Upgrade to video script: Creating Sequelize model and manipulating data

### ISSUE THREAD

**Issue by avishekjana** [pupilfirst/wd201-scripts#180]
@mjzac 

- First, I think this script should be upgraded to Video content, as we are introducing an important concept here.
- Then, in this script, nowhere it's mentioned that, how to execute & check the code written here. Maybe, you can add guide  to run these codes in terminal.

**Comment by reenas** [comment]
@mjzac I have seen both the videos. They both look okay and I will upload them to LMS.

In second one on _sequlize-crud_ here are my comments:

- When you mention IIFE and show its definition, spend some time to explain why is this being used and what will happen if we don't.
- Similarly when you say let's create a static method or an instance method, explain why you are choosing to do this and why is it important. You might have added text in previous lessons, but reiterating when something is being used is very useful in helping students understand why a particular thing is this way. 

We can add these explanatory texts on LMS for now.

**Comment by mjzac** [comment]
@reenas I have added a small explainer video on why we had to use the IIFE. Please do review https://drive.google.com/drive/folders/1ksFaIMtC4F7Z6XIZf338BTHr5aezcia5?usp=sharing

**Comment by reenas** [comment]
@mjzac This is cool, very clear demo of IIFE 👏. I will upload this on LMS
