### ISSUE TITLE
Add presentation link to L3 - What is event loop

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#182]
@avishekjana In [What is event loop](https://github.com/pupilfirst/wd201-scripts/blob/v2/nodejs-deep-dive/what-is-event-loop/README.md), 

>Action: Show the presentation 1 of call stack from google drawing.

>Action: Show the presentation 2 of call stack from google drawing.

Please link the presentations (with view permission to all) that you intend to show in this lesson itself. Reason being, the students in TA training will need to see this to understand/comment.

**Comment by avishekjana** [comment]
ok

**Comment by avishekjana** [comment]
Created an animated slide for call stack: https://docs.google.com/presentation/d/1qFQRZ-8fkkm-LN2jwKE-XC8tiV9-H5XU4XcvZs_geO8/edit?usp=sharing

Previously I've created 3 google drawings, but later I found that it will be better if I could animate the call stack, so created this one.
