### ISSUE TITLE
Add image in L4 - TDD

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#187]
@mjzac In [TDD workflow](https://github.com/pupilfirst/wd201-scripts/blob/v2/testing/tdd/README.md), the TDD workflow image is pending to be included.

> TODO: Insert image of TDD workflow

**Comment by mjzac** [comment]
Fixed by https://github.com/pupilfirst/wd201-scripts/pull/199

**Comment by reenas** [comment]
@mjzac The image is not visible in the content at all. It does not get downloaded too when I try. Did you test it after uploading?

![Image](https://user-images.githubusercontent.com/3531077/182350647-a7e241e4-09d8-45e8-868e-1cf45e8858b0.png)
