### ISSUE TITLE
Some text edit in  L5 - Connect to Database and create table 

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#190]
In [Connect to Database and create table](https://github.com/pupilfirst/wd201-scripts/blob/v2/databases/connect-to-db/README.md), the table attributes defined in the code in `createTodosTable.js` is different from the shell output mentioned below - including table name. 

Also, in `First, you have to modify connectDB.js to expose two functions.` what does it mean to expose functions? If this is covered earlier, and I have missed, please ignore.

**Comment by mjzac** [comment]
Fixed by https://github.com/pupilfirst/wd201-scripts/pull/198
