### ISSUE TITLE
Some details to add in L5  - Separate DB

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#202]
In [separate db](https://github.com/pupilfirst/wd201-scripts/blob/v2/databases/separate-db/README.md) lesson, 

>Then we will add a script `pretest` which will run before running `test` script. Here we will delete the existing database from previous run as we need clean slate before each test run.

I am not clear why clean state is needed before test run.

**Comment by mjzac** [comment]
@reenas The lesson begins with explanation that while testing, we will create or delete tables. 

>We use database to persist data. While running tests, we might insert or delete rows from the database. So it is a common practise to use a separate database for the purpose of testing. By doing this, we can easily create or destroy tables with peace of mind.

Should I add more context here?

**Comment by reenas** [comment]
@mjzac So basically we want to use a`test` database for testing. Every time we use it, we delete the existing database first and create a fresh database and run tests?

**Comment by mjzac** [comment]
@reenas Yes, by doing so, the development and production data, which would be in it's own separate databases, won't get affected.
