### ISSUE TITLE
ReferenceError: path is not defined in EJS template

### ISSUE THREAD

**Issue by avishekjana** [pupilfirst/wd201-scripts#217]
In the "Use view templates for common elements like headers and footers." script under "EJS Templating" section, after adding the following like in index.js,

`app.use(express.static(path.join(__dirname, "public")));`

I'm getting the following error: 

app.use(express.static(path.join(__dirname, "public")));
                       ^

**ReferenceError: path is not defined**

**Comment by reenas** [comment]
This has been addressed.
