### ISSUE TITLE
L1: Update Microsoft edge JS engine to V8

### ISSUE THREAD

**Issue by rabilrbl** [pupilfirst/wd201-scripts#219]
> L1: Intro to NodeJS

Modern Microsoft Edge browser is based on chromium hence uses V8, only legacy Microsoft Edge uses Chakra JS engine.
![image](https://user-images.githubusercontent.com/63334479/185936389-eb6d230e-0498-41ab-b0cd-102650d9f8e0.png)

**Comment by reenas** [comment]
This is fixed in the content. Thanks for creating the issue @rabilrbl
