### ISSUE TITLE
[Video] Add tests to Express.js application

### ISSUE THREAD

**Issue by mjzac** [pupilfirst/wd201-scripts#233]

**Comment by mjzac** [comment]
@reenas Please review https://drive.google.com/drive/folders/1oLXkPS2go_k2BF24XxAfJXzQR8UzSf2X?usp=sharing

**Comment by reenas** [comment]
@mjzac Sure, does this take care of the recent feedback from Vamsi already?

**Comment by reenas** [comment]
LGTM @mjzac, I have added this to LMS. Thanks.
