### ISSUE TITLE
[Video] Adding a new to-do with the help of form

### ISSUE THREAD

**Issue by mjzac** [pupilfirst/wd201-scripts#234]

**Comment by mjzac** [comment]
@reenas Please review https://drive.google.com/drive/folders/1R49fpcuk7HuVo7RA1eWA7HyBQhrwVxRM?usp=sharing In the folder there are two videos. Please review the `new-todo-using-form`. The other one can be deleted. I was not able to delete it.

**Comment by reenas** [comment]
@mjzac I have added this to LMS and deleted the other file from drive
