### ISSUE TITLE
Make tests pass in L10 content

### ISSUE THREAD

**Issue by mjzac** [pupilfirst/wd201-scripts#247]
Tests are now failing with modifications in L10. Add a lesson to fix it.

**Comment by avishekjana** [comment]
@mjzac can you start work on it?

**Comment by mjzac** [comment]
Yes, I will prepare the content and record the video once @vikispeaks updates the code.

**Comment by mjzac** [comment]
@reenas Please review https://drive.google.com/drive/folders/1H7d-L7Yz0nXUBXT6AMu8kviB6-QyGVsT?usp=share_link

**Comment by reenas** [comment]
@mjzac I have added this on LMS
