### ISSUE TITLE
What is Closure in JavaScript?

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#44]

**Comment by avishekjana** [comment]
@reenas I've already raised a PR (https://github.com/pupilfirst/wd201-scripts/pull/27), Melson reviewed it. I've revised it based on feedbacks given. Once it's reviewed again and merged, I'll let you know.

**Comment by reenas** [comment]
@avishekjana The PR is merged, I believe? You can close this issue.

**Comment by avishekjana** [comment]
OK
