### ISSUE TITLE
Add two features: create a new to-do, and mark an existing to-do as completed

### ISSUE THREAD

**Issue by reenas** [pupilfirst/wd201-scripts#64]

**Comment by avishekjana** [comment]
@reenas Previously I've written this script and directly pushed it to v2 branch by mistake. Now, I've created a new branch and raised a fresh PR(https://github.com/pupilfirst/wd201-scripts/pull/126).

**Comment by avishekjana** [comment]
PR merged with v2 branch, so closing it now.
