### ISSUE TITLE
L10: Introduction

### ISSUE THREAD

**Issue by hosting-sv** [pupilfirst/wd201-scripts#80]

**Comment by avishekjana** [comment]
PR(https://github.com/pupilfirst/wd201-scripts/pull/127) under review.

**Comment by avishekjana** [comment]
@reenas The script has been revised and merged, closing it.

**Comment by reenas** [comment]
@avishekjana Since the video is very short, could you quickly record a fresh one. The old video mentions the course as SaaS201, since we are making the course afresh, this short video will be easy to get done in my opinion.

**Comment by reenas** [comment]
@vikispeaks has made this video and it is uploaded on LMS
